# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [209]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [210]:
A = np.arange(1, 16).reshape(3,5)

In [211]:

dimension = A.ndim
shape = A.shape
size = A.size
datatype = A.dtype

print(f"Dimension: {dimension}")
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Data type: {datatype}")



Dimension: 2
Shape: (3, 5)
Size: 15
Data type: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [212]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [213]:
elementwise_subtraction = B-C
print("\nElementwise Subtraction (B-C):")
print(elementwise_subtraction)

elementwise_multiplication = B*C
print("\nElementwise Multiplication (B*C):")
print(elementwise_multiplication)

matrix_multiplication = B*C
print("\nMatrix Multiplication (B @ C):")
print(matrix_multiplication)









Elementwise Subtraction (B-C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B*C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [214]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [215]:
exp_B = np.exp(B)
print ("\nEponentiated Matrix (np.exp(B)):")
print (exp_B)

min_value = np.min(B)
print("\nMinimum value in the whole matrix:")
print(min_value)

min_value_rows = np.min(B, axis=1)
print("\nminimum value in each wor:")
print(min_value_rows)

min_value_columns = np.min(B,axis=0)
print("\nMinimun value each column:")
print(min_value_columns)

min_index = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix:")
print(min_index)

min_index_rows = np.argmin(B, axis=1)
print("\nIndex of the minimum value in each row:")
print(min_index_rows)

total_sum = np.sum(B)
print("§nSum of all elements:")
print(total_sum)

mean_columns = np.mean(B, axis=0)
print("n\nMean for each column:")
print(mean_columns)

median_columns = np.median(B, axis=0)
print("\nMedian for each column:")
print(median_columns)



Eponentiated Matrix (np.exp(B)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:
1

minimum value in each wor:
[1 4 7]

Minimun value each column:
[1 2 3]

Index of the minimum value in the whole matrix:
0

Index of the minimum value in each row:
[0 0 0]
§nSum of all elements:
45
n
Mean for each column:
[4. 5. 6.]

Median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [216]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [217]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [218]:
# When you provide fewer indicas then axes when slicing, you select all the elements along the unspecified axes. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [219]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [220]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [221]:
print("\nIterating elementwise with np.nditer():")
for element in np.nditer(A):
    print (element)
    


Iterating elementwise with np.nditer():
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [222]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [223]:
# The code reshapes an 1D array into an 3D array with three axes


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [224]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [225]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [226]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [227]:
def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isintance(mat2, np.ndarray):
        raise ValueError("both inputs must be of type numpy.ndarray")
    
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'")
    
    if operation == "add":
        if mat1.shape != mat2.shape:
            raise ValueError("Matrices must have the same sixe for addition")
        return mat1 + mat2
    
    elif operation == "multuply":
        if mat1.shape[1] !=mat2.shape[0]:
            raise ValueError("number of columns in the first matrix must equal the number of rows in the second matrix for multiplication")
        return mat1 @ mat2
    

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [228]:
x = np.array([4,3])
dimension = x.ndim


print ("Svar uppgift 10.1.1")

print()

print (" (a) Dimension:", dimension)

print()

resultat = 5*x

print (" (b) resultat av 5x:", resultat)

print()

resultat = 3*x

print (" (c) resultat av 3x:", resultat)

print()

resultat = 5*x + 3*x

print ("(d) resultat av 5x + 3x:", resultat)

print()

resultat = 8*x

print ("(e) resultat av 8x:", resultat)

print()

resultat = 4*x - x

print ("(f) resultat av 4x - x:", resultat)

print()

x_transposed = x.T
x_column_vector = x.reshape (-1,1)

print ("(g) Transponent av x")
print(x_column_vector)
print ("den nya dimensionen efter transponeringen är 2 × 1")

print()

print ("(h) x+x^T är inte definerat då dom har två olika dimensioner")

norm_x = np.linalg.norm(x)
print ("(i) ||x||:", norm_x)

print()

print ("Svar uppgift 10.1.2")

v = np.array([3,7,0,11]).reshape(-1,1)

print ("(a)vektorn v har dimension 4")

print()

resultat = 2*v

print (" (b) resultat av 2x:", resultat)

print()

resultat = 5*v+2*v

print ("(c) resultat av 5v+2v:", resultat)

print()

resultat = 4*v - 2*v

print ("(d) resultat av 4v- 2v:", resultat)

print()

v = np.array([3,7,0,11]).reshape(-1,1)
print ("(e) V^T = (3,7,0.11) pch har 1 dimension efter transponering")

norm_v = np.linalg.norm(v)
print ("(f) ||v||:", norm_v)

print()


print("svar till uppgift 10.1.3")

v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

norm_v1 = np.linalg.norm(v1)
print ("(a) ||v1||:", norm_v1)

norm_v2 = np.linalg.norm(v2)
print ("(b) (||v1||-||v2||):"), norm_v2






















Svar uppgift 10.1.1

 (a) Dimension: 1

 (b) resultat av 5x: [20 15]

 (c) resultat av 3x: [12  9]

(d) resultat av 5x + 3x: [32 24]

(e) resultat av 8x: [32 24]

(f) resultat av 4x - x: [12  9]

(g) Transponent av x
[[4]
 [3]]
den nya dimensionen efter transponeringen är 2 × 1

(h) x+x^T är inte definerat då dom har två olika dimensioner
(i) ||x||: 5.0

Svar uppgift 10.1.2
(a)vektorn v har dimension 4

 (b) resultat av 2x: [[ 6]
 [14]
 [ 0]
 [22]]

(c) resultat av 5v+2v: [[21]
 [49]
 [ 0]
 [77]]

(d) resultat av 4v- 2v: [[ 6]
 [14]
 [ 0]
 [22]]

(e) V^T = (3,7,0.11) pch har 1 dimension efter transponering
(f) ||v||: 13.379088160259652

svar till uppgift 10.1.3
(a) ||v1||: 7.14142842854285
(b) (||v1||-||v2||):


(None, 3.872983346207417)

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [229]:
import numpy as np

matrix_A = np.array([[2, 1, -1],[1, -1, 1]])

matrix_B = np.array([[4, -2, 1],[2, -4, -2]])

matrix_C = np.array([[1, 2],[2, 1]])

matrix_D = np.array([[3, 4],[4, 3]])

matrix_E = np.array([[1],[2]])

matrix_I = np.array([[1, 0],[0, 1]])

resultat = 2*matrix_A
print ("a", resultat)

print()


resultat = (matrix_B)-(2*matrix_A)
print("b", resultat)

print()


print("c är ej definerat")

print()

resultat = (2*matrix_D)-(3*matrix_C)
print("d", resultat)

print()

transposed_D = matrix_D.T
resultat = (transposed_D)+(2*matrix_D)
print("e", resultat)

print()

transposed_C = matrix_C.T
resultat = (2*transposed_C)-(2*transposed_D)
print("f", resultat)

print()

print ("(g) är inte definerat")

print()

print ("(h) är inte definerat")

print ()

resultat = (matrix_D)@(matrix_C)
print("i", resultat)

print()

resultat = (matrix_I)@(matrix_C)
print("k", resultat)

print()

transposed_B=matrix_B.T

resultat = (matrix_A)@(transposed_B)
print("I", resultat)

print()

print("lösning för uppgift 10.2.2")

matrix_A1 = np.array([[2, 3, 4],[5, 4, 1]])
transposed_A1=matrix_A1.T

resultat = (matrix_A1)@(transposed_A1)
print(resultat)

print()
print("lösning för uppgift 10.2.3")

matrix_A = np.array([[1,2],[2,4]])
matrix_B = np.array([[2,1], [1,3]])
matrix_C = np.array([[4,3], [0,2]])

resultat = (matrix_A)@(matrix_B)
print("(AB)", resultat)

print("vilket är samma som")

resultat = (matrix_A)@(matrix_C)
print("(AC)", resultat)


























a [[ 4  2 -2]
 [ 2 -2  2]]

b [[ 0 -4  3]
 [ 0 -2 -4]]

c är ej definerat

d [[3 2]
 [2 3]]

e [[ 9 12]
 [12  9]]

f [[-4 -4]
 [-4 -4]]

(g) är inte definerat

(h) är inte definerat

i [[11 10]
 [10 11]]

k [[1 2]
 [2 1]]

I [[5 2]
 [7 4]]

lösning för uppgift 10.2.2
[[29 26]
 [26 42]]

lösning för uppgift 10.2.3
(AB) [[ 4  7]
 [ 8 14]]
vilket är samma som
(AC) [[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [230]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [231]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

is_v1_view = v1.base is None
is_v2_view = v2.base is not None

print ("Is v1 a view?" , not is_v1_view)
print("Is v2 a view?", is_v2_view)


None
[0 1 2 3]
Is v1 a view? False
Is v2 a view? True


In [232]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
